### PR TITLE
Corrected issue with List Servers function

### PR DESCRIPTION
**Pull request by nwright-nz**
Added ECONOMY disk speed to the VirtualMachineDiskSpeed enum - this corrects an issue with the List Servers call failing.
Also added extra functionality to the Server resource by implementing server start and shutdown functions.

### CODE REVIEW

**Comment by jeffstoner** [comment]
There is no "LOW" disk speed. There is, currently, only "ECONOMY", "STANDARD", and "HIGHPERFORMANCE".
Change LOW to ECONOMY instead.
For reference, see https://docs.mcp-services.net/pages/viewpage.action?pageId=3015251

**Comment by tintoy** [comment]
Thanks! Looks good :)

**Comment by tintoy** [comment]
(sorry for the delay - have a cold at the moment :-/ )

**Comment by tintoy** [comment]
BTW, feel free to pull this into [cloudcontrol-powershell-core](https://github.com/DimensionDataResearch/cloudcontrol-powershell-core). Or if you don't have time, let me know and I'll have a go.

**Comment by nwright-nz** [comment]
Sure thing. And I'll clean up that LOW disk speed entry as well as per the comment made by  @jeffstoner  - I thought that speed was there for some kind of backwards compatibility, so didn't remove it...but yeah, after looking through old api documentation there is no mention of it.

**Comment by tintoy** [comment]
Yeah, sorry, that was my doing (brain-fart). I actually know it's `ECONOMY` because I had to implement it for our Go client. Woops :)

**Pull request merged**
